# Generated by Django 2.2.12 on 2020-07-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/'),
        ),
    ]
