# Generated by Django 2.2.12 on 2020-07-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.BinaryField(blank=True, default='default.png'),
        ),
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.BinaryField(blank=True),
        ),
    ]
