# Generated by Django 2.2.12 on 2020-07-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200724_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='logo',
        ),
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.URLField(blank=True, default='default.png'),
        ),
        migrations.AddField(
            model_name='product',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
