# Generated by Django 2.2.12 on 2020-08-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
