# Generated by Django 2.2.12 on 2020-09-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200917_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(max_length=300),
        ),
    ]
