# Generated by Django 2.2.12 on 2020-11-01 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20200917_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Qty',
            field=models.IntegerField(help_text='Qty'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(help_text='Category', max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(help_text='Color', max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='img_url',
            field=models.URLField(blank=True, default='default.png', help_text='Image Url'),
        ),
        migrations.AlterField(
            model_name='order',
            name='logo_url',
            field=models.URLField(blank=True, help_text='logo url'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(help_text='Price', max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(help_text='size', max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='statue',
            field=models.CharField(choices=[('Reviewing', 'Reviewing'), ('Reviewed', 'Reviewed'), ('Charging', 'Charging')], help_text='Statue', max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(help_text='Title', max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.URLField(help_text='Url'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(help_text='Address', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(help_text='Fullname', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(help_text='Promo Code', max_length=500)),
                ('order', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to='core.Order')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OnlinePrice', models.CharField(default='Calculating', help_text='Online Price', max_length=100)),
                ('Customs', models.CharField(default='Calculating', help_text='Customs', max_length=100)),
                ('VAT', models.CharField(default='Calculating', help_text='VAT', max_length=100)),
                ('EShhnliFees', models.CharField(default='Calculating', help_text='E-Shhnli Fees', max_length=100)),
                ('IntShipping', models.CharField(default='Calculating', help_text='Int-Shipping', max_length=100)),
                ('DeliveryFees', models.CharField(default='Calculating', help_text='Delivery Fees', max_length=100)),
                ('Subtotal', models.CharField(default='Calculating', help_text='Subtotal', max_length=100)),
                ('Total', models.CharField(default='Calculating', help_text='Total', max_length=100)),
                ('order', models.ForeignKey(help_text='Order', on_delete=django.db.models.deletion.CASCADE, to='core.Order')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
