# Generated by Django 2.2.12 on 2020-11-02 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_auto_20201101_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fullname',
        ),
        migrations.AddField(
            model_name='profile',
            name='ZIP',
            field=models.CharField(default='', help_text='ZIP', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address_1',
            field=models.CharField(default='', help_text='Address 1', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address_2',
            field=models.CharField(default='', help_text='Address 2', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='', help_text='Country', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='', help_text='State', max_length=300),
            preserve_default=False,
        ),
    ]
