# Generated by Django 2.2.12 on 2020-11-03 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_auto_20201102_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Eslam Ramadan', help_text='Full Name', max_length=300),
            preserve_default=False,
        ),

    ]
