# Generated by Django 2.2.12 on 2020-11-05 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_auto_20201103_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='order',
            field=models.ForeignKey(help_text='Order', on_delete=django.db.models.deletion.CASCADE, to='core.Order'),
        ),

    ]
