# Generated by Django 2.2.12 on 2020-11-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_commercialorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommercialOrder',
        ),
    ]
