# Generated by Django 2.2.12 on 2020-11-06 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_delete_commercialorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=300)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity')),
                ('price', models.IntegerField(default=1, help_text='Price')),
                ('details', models.TextField(help_text='Details')),
                ('file', models.FileField(help_text='Details File', upload_to='files/')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
