# Generated by Django 2.2.12 on 2020-11-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_commercialorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialorder',
            name='file',
            field=models.FileField(blank=True, help_text='Details File', null=True, upload_to='files/'),
        ),
    ]
