# Generated by Django 2.2.12 on 2020-11-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201106_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.CharField(blank=True, help_text='Promo Code', max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
