# Generated by Django 2.2.12 on 2020-11-09 13:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_subscribtion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'state', 'full_name', 'country', 'ZIP')},
        ),
    ]
