# Generated by Django 2.2.12 on 2020-11-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201109_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribtion',
            name='subscribe',
            field=models.CharField(choices=[(1, 'Platinum'), (3, 'No Limits'), (2, 'More Discount')], help_text='Subscribe', max_length=1),
        ),
    ]
