# Generated by Django 2.2.12 on 2020-11-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201109_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribtion',
            name='subscribe',
            field=models.CharField(choices=[('More_Discount', 'More Discount'), ('No_Limits', 'No Limits'), ('Platinum', 'Platinum')], help_text='Subscribe', max_length=1),
        ),
    ]
