# Generated by Django 2.2.12 on 2020-11-09 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_auto_20201109_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribtion',
            name='subscribe',
            field=models.CharField(choices=[('More_Discount', 'More Discount'), ('No_Limits', 'No Limits'), ('Platinum', 'Platinum')], help_text='Subscribe', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='subscribtion',
            unique_together={('user', 'subscribe')},
        ),
    ]
