# Generated by Django 2.2.12 on 2020-11-10 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20201109_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscribtion',
            name='subscribe',
            field=models.CharField(choices=[('No_Limits', 'No Limits'), ('More_Discount', 'More Discount'), ('Platinum', 'Platinum')], help_text='Subscribe', max_length=50),
        ),
    ]
