# Generated by Django 2.2.12 on 2020-11-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20201110_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribtion',
            name='subscribe',
            field=models.CharField(choices=[('Platinum', 'Platinum'), ('No_Limits', 'No Limits'), ('More_Discount', 'More Discount')], help_text='Subscribe', max_length=50),
        ),
    ]
