# Generated by Django 2.2.12 on 2020-11-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20201110_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_1',
            field=models.CharField(help_text='Address 1', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_2',
            field=models.CharField(help_text='Address 2', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscribtion',
            name='subscribe',
            field=models.CharField(choices=[('More_Discount', 'More Discount'), ('No_Limits', 'No Limits'), ('Platinum', 'Platinum')], help_text='Subscribe', max_length=50),
        ),
    ]
