# Generated by Django 2.2.12 on 2020-11-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20201110_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribtion',
            name='subscribe',
            field=models.CharField(choices=[('Platinum', 'Platinum'), ('More_Discount', 'More Discount'), ('No_Limits', 'No Limits')], help_text='Subscribe', max_length=50),
        ),
    ]
