# Generated by Django 2.2.12 on 2020-11-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20201111_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.URLField(help_text='Url', max_length=1000),
        ),
    ]
