# Generated by Django 2.2.12 on 2020-11-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20201113_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialorder',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='commercialorder',
            name='price',
            field=models.IntegerField(default=1, help_text='Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(help_text='Price', max_length=300),
        ),
    ]
