# Generated by Django 2.2.12 on 2020-11-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20201113_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price', max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price', max_digits=6),
        ),
    ]
