# Generated by Django 2.2.12 on 2020-11-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20201113_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialorder',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Price', max_digits=10),
        ),
    ]
