# Generated by Django 2.2.12 on 2020-11-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20201113_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialorder',
            name='price',
            field=models.CharField(help_text='Price', max_length=300),
        ),
    ]
