# Generated by Django 2.2.12 on 2020-11-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20201113_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='Discount',
            field=models.CharField(default='Calculating', help_text='Discount', max_length=100),
        ),
    ]
